name: LookUp Monitor

on:
  schedule:
    - cron: '0 3,13 * * *' # 每天北京时间 11点和 21点运行
  workflow_dispatch:      # 允许手动测试

jobs:
  build:
    runs-on: ubuntu-latest
    # 强制声明权限
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 使用最新版

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run monitor
        env:
          SC_SENDKEY: ${{ secrets.SC_SENDKEY }}
        run: python monitor.py

      - name: Save history file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # 检查文件是否存在，如果存在才提交
          if [ -f history.txt ]; then
            git add history.txt
            git commit -m "Update history" || echo "No changes to commit"
            git push
          fi
